# Generated by Django 5.0.1 on 2024-01-05 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=250)),
                ('Product_Price', models.FloatField(blank=True, null=True)),
                ('Product_Image', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Email', models.CharField(max_length=250)),
                ('User_Name', models.CharField(max_length=300)),
                ('User_Password', models.CharField(max_length=250)),
                ('User_Details', models.CharField(max_length=1000)),
                ('User_Orders', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Details', models.CharField(max_length=1000)),
                ('Order_Status', models.CharField(max_length=250)),
                ('Order_Shipping_Status', models.CharField(max_length=250)),
                ('User_Details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coffee_app.user')),
            ],
        ),
    ]
