# Generated by Django 5.0.1 on 2024-01-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coffee_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='User_Details',
            new_name='User_ID',
        ),
    ]
